language: php
sudo: required
dist: precise

matrix:
  include:
    - php: 5.4
      env: DB=none;NOTESTS=1
  fast_finish: true

services:
  - redis-server

install:
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION $NOTESTS

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION $NOTESTS
  - phantomjs --webdriver=8910 > /dev/null &

script:
  - sh -c "set -x;if [ '$NOTESTS' = '1' -a '$TRAVIS_PULL_REQUEST' != 'false' ]; then git fetch --unshallow && git-tools/commit-msg-hook-range.sh origin/$TRAVIS_BRANCH..FETCH_HEAD; fi"

